eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      enabled: true

  instance:
      statusPageUrl: http://${eureka.hostname}/info
      healthCheckUrl: http://${eureka.hostname}/health
      homePageUrl: http://${eureka.hostname}/