spring:
  application:
    name: eureka-provider

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
#      enabled: true
#
#  instance:
#      statusPageUrl: http://${eureka.hostname}/info
#      healthCheckUrl: http://${eureka.hostname}/health
#      homePageUrl: http://${eureka.hostname}/
#
#pring.application.name=spring-cloud-producer
#server.port=9000
#eureka.client.serviceUrl.defaultZone=http://localhost:8000/eureka/